import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import NavBar from './components/NavBar'
import Footer from './components/Footer/page'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className='inter.className'>
          <NavBar />
          {/* <main className='container'>
            <div className='flex items-start justify-center min-h-screen'>
              <div className='mt-20'>{children}</div>
            </div>
          </main> */}
          {children}
          <Footer />
          </body>
      </html>
    </ClerkProvider>
  )
}
